baseurl = "http://dentaldatascience.org/"
DefaultContentLanguage = "en"
#DefaultContentLanguage = "ja"
title = "Dental Data Science"
theme = "beautifulhugo"
metaDataFormat = "yaml"
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
#pygmentsUseClassic = true
#pygmentOptions = "linenos=inline"
disqusShortname = "dental-data-science"
#googleAnalytics = "XXX"

[Params]
  subtitle = "Tools and tips to manipulate dental research data, create visualizations, and to communicate information with R"
  logo = "img/dds_4.png"
  favicon = "img/dds_3.png"
  dateFormat = "January 2, 2006"
  commit = false
  rss = true
  comments = true
  readingTime = true
  useHLJS = true
  gcse = "001914880863475946784:jaiqxnvieeu" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"

#[[Params.bigimg]]
#  src = "img/triangle.jpg"
#  desc = "Triangle"
# [[Params.bigimg]]
#  src = "img/sphere.jpg"
#  desc = "Sphere"
#  # position: see values of CSS background-position.
#  position = "center top"
# [[Params.bigimg]]
#  src = "img/hexagon.jpg"
#  desc = "Hexagon"

[Author]
  name = "Sergio Uribe"
  website = "http://www.sergiouri.be/"
  email = "sergio.uribe@gmail.com"
#  facebook = "username"
#  googleplus = "+username" # or xxxxxxxxxxxxxxxxxxxxx
  github = "sergiouribe"
#  gitlab = "username"
  twitter = "dentaldatasci"
#  reddit = "username"
  linkedin = "sergiouribe"
#  xing = "username"
  stackoverflow = "users/7617/sergiouribe"
#  snapchat = "username"
#  instagram = "username"
#  youtube = "user/username" # or channel/channelname
#  soundcloud = "username"
#  spotify = "username"
#  bandcamp = "username"
#  itchio = "username"
#  vk = "username"
#  paypal = "username"
#  telegram = "username"

# [[menu.main]]
#    name = "Blog"
#    url = ""
#    weight = 1

[[menu.main]]
    name = "About"
    url = "page/about/"
    weight = 3
    
[[menu.main]]
    name = "Links"
    url = "page/links/"
    weight = 3

[[menu.main]]
    name = "Categ"
    url = "categories"
    weight = 3

[[menu.main]]
    name = "Tags"
    url = "tags"
    weight = 3
